FROM php:8.2-fpm

WORKDIR var/www

RUN apt-get update && apt-get install -y \
	build-essential \
	libpng-dev \
	libjpeg-dev \
	libonig-dev \
	libxml2-dev \
	zip unzip curl git \
	&& docker-php-ext-install pd0_mysql mbstring exif pentl bemath gd

COPY ./var/www

RUN curl -sS http://getcomposer.org/istaller | php \
--install-dir=/usr/local/bin--filename=composer

RUN composer install

CMD["php-fpm"]